version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
        MYSQL_DATABASE: hipsyimage
        MYSQL_ROOT_PASSWORD: p4j4m4sII!
    command: --bind-address=*
    networks:
        - carousel_net
    ports: 
      - '3306:3306'
    expose: 
      - '3306'

  client:
    depends_on:
      - 'mysql'
    build:
        context: .
    networks:
        - carousel_net
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
networks:
    carousel_net:

